spring.application.name=coupon
springdoc.override-with-generic-response=false
springdoc.default-produces-media-type=application/json
springdoc.packages-to-scan=com.eduardo.coupon.infrastructure.web
spring.datasource.url=jdbc:h2:mem:coupon
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
